"""Add 3x-ui integration fields and traffic_records table

Revision ID: 857a6c7ca703
Revises: 001
Create Date: 2026-03-04 18:24:21.320993

"""
from alembic import op
import sqlalchemy as sa


revision = '857a6c7ca703'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('upload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('download_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('cost_share', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_records_id'), 'traffic_records', ['id'], unique=False)
    op.create_index('ix_traffic_records_user_month', 'traffic_records', ['user_id', 'month'], unique=True)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('xui_client_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('xui_inbound_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('xui_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'xui_email')
    op.drop_column('users', 'xui_inbound_id')
    op.drop_column('users', 'xui_client_id')
    op.drop_column('users', 'email')
    op.drop_index('ix_traffic_records_user_month', table_name='traffic_records')
    op.drop_index(op.f('ix_traffic_records_id'), table_name='traffic_records')
    op.drop_table('traffic_records')
    # ### end Alembic commands ###
